modLoader="lowcodefml"
loaderVersion="*"
issueTrackerURL="https://github.com/gjhihihi/Tinkers-Ancient-Tools-Rebuilding/issues"
license="MIT"
[[mods]]
    modId="tinkers_atr"
    version="0.0.2"
    displayName="Tinkers: Ancient Tools Rebuilding"
    authors="gjhi"
    description='''
    An addon for Tinkers' Construct that make ancient tools craftable.
    '''
[[dependencies.tinkers_atr]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.10.2.146,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tinkers_atr]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"
